stilistische Änderungsvorschläge L499 - 524
TQueV/covid-19 pull request #28
Opened 2020-05-06 11:41 UTC by jahfaby

2020-05-06 12:16 UTC, herrhundt approved these changes

2020-05-06 16:39 UTC, TQueV requested changes

2020-05-06 16:39 UTC, TQueV commented on words/words.md
> +Pandemien sind wie Poker: **Wette nur, wenn du dir zu 95% sicher bist und du sonst alles verlieren wirst.** Wie aus einem aktuellen Artikel[^precautionary] über Masken im British Medical Journal herv
Top!

2020-05-06 16:39 UTC, TQueV commented on words/words.md
> +Kosten: Wenn Alltagsmasken (die etwa ~2/3 so effektiv wie chirurgische Masken[^homemade]) sind), dann ist das superbillig. Wenn chirurgische Masken, dann wird das teurer, aber immer noch ziemlich bil
Vorschlag: "Wenn es sich um chirurgische Masken handelt, wird es teurer, aber immer noch ziemlich billig."

2020-05-06 19:05 UTC, jahfaby commented on words/words.md
> +Kosten: Wenn Alltagsmasken (die etwa ~2/3 so effektiv wie chirurgische Masken[^homemade]) sind), dann ist das superbillig. Wenn chirurgische Masken, dann wird das teurer, aber immer noch ziemlich bil
Ja, können wir gerne machen. Ich habe nur keine Ahnung, wie ich das hier mache. :/ :)

2020-05-07 06:59 UTC, herrhundt commented on words/words.md
> +Kosten: Wenn Alltagsmasken (die etwa ~2/3 so effektiv wie chirurgische Masken[^homemade]) sind), dann ist das superbillig. Wenn chirurgische Masken, dann wird das teurer, aber immer noch ziemlich bil
erledigt

2020-05-07 07:00 UTC, herrhundt approved these changes

2020-05-07 07:00 UTC, merged