Update words.md - stilistische Änderungsvorschläge L573 - 608
TQueV/covid-19 pull request #31
Opened 2020-05-06 12:27 UTC by jahfaby

2020-05-06 13:33 UTC, herrhundt approved these changes

2020-05-07 12:02 UTC, jkoelling commented
@jahfaby Danke für die Korrekturen der Zeichensetzung, dass ist meine große Schwäche 🙈

2020-05-07 12:11 UTC, jkoelling requested changes

2020-05-07 12:11 UTC, jkoelling commented on words/words.md
> +Für die folgenden Simulationen, lass' uns annehmen dass es 1 Jahr ist.
```suggestion
Für die folgenden Simulationen, lass uns annehmen dass es 1 Jahr ist. 
```
Hab noch mal nachgesehen und soweit ich das verstehe kommt da kein Apostroph hin. Lasse mich mit ner Quelle gerne belehren.

2020-05-07 12:11 UTC, jkoelling commented on words/words.md
> +**Hier ist eine Simulation, die mit 100% <icon r></icon> anfängt**, dann exponentiell zerfällt zu nach einem Jahr anfälligen, nicht immunen <icon s></icon>s, im *Mittel*, mit Abweichungen:
Bin hier weder mit meiner noch mit der neuen Variante ganz glücklich, das Original ist hier auch nicht so schön. Finde die neue Variante aber etwas besser und mir fällt nichts ein was alle Probleme lösen würde.

2020-05-07 12:12 UTC, jkoelling commented
Wir müssen bei den übersetzen Zitaten auch noch mal die Originale einfügen. Das ist allerdings gerade nicht konsistent und ich würde das lieber in einem gemeinsamen PR für den ganzen Text am Ende gerade ziehen.

2020-05-07 22:28 UTC, TQueV commented on words/words.md
> +**Hier ist eine Simulation, die mit 100% <icon r></icon> anfängt**, dann exponentiell zerfällt zu nach einem Jahr anfälligen, nicht immunen <icon s></icon>s, im *Mittel*, mit Abweichungen:
Vorschlag: (Es soll doch gesagt werden dass die Kurve zerfällt und die Personen nach einem Jahr die Immunität verlieren, richtig? Das sind 2 verschiedene Informationen, die im Original irgendwie unglücklich vermischt sind.)

**Hier ist eine Simulation, die mit 100% <icon r></icon> beginnt** und exponentiell zerfällt, mit im *Mittel* nach einem Jahr nicht mehr immunen, wieder anfälligen <icon s></icon>s, mit Abweichungen:

2020-05-07 23:44 UTC, TQueV commented on words/words.md
> +Für die folgenden Simulationen, lass' uns annehmen dass es 1 Jahr ist.
Hätte gedacht dass man den Apostroph verwenden kann, aber du hast absolut recht!

2020-05-08 00:48 UTC, TQueV commented on words/words.md
>  * COVID-19 ist am engsten mit SARS verwandt, welches den Überlebenden 2 Jahre Immunität brachte.[^SARS immunity]
```suggestion
* COVID-19 ist am engsten mit SARS verwandt, welches die Überlebenden für 2 Jahre immun machte.[^SARS immunity]
```

2020-05-08 00:48 UTC, TQueV commented on words/words.md
> +* Die Coronaviren, die "normale" Erkältungen auslösen, machen dich 8 Monate immun.[^cold immunity]
```suggestion
* Die Coronaviren, die "normale" Erkältungen auslösen, machen dich für 8 Monate immun.[^cold immunity]
```

2020-05-08 00:50 UTC, TQueV commented on words/words.md
> +* Eine *noch nicht fachlich begutachtete* Studie an Affen zeigte Immunität gegen COVID-19 Coronaviren für mindestens 28 Tage.[^monkeys]
```suggestion
* Eine *noch nicht fachlich begutachtete* Studie an Affen zeigte Immunität gegen COVID-19-Coronaviren für mindestens 28 Tage.[^monkeys]
```

2020-05-08 00:52 UTC, TQueV commented on words/words.md
> +[^unclear]: Nachdem eine Person einen Virus abgewährt hat, neigen Viruspartikel dazu, eine Weile zu verbleiben. Diese Partikel können keine Infektion auslösen aber sie können zu einem positiven Teste
```suggestion
[^unclear]: Nachdem eine Person einen Virus abgewehrt hat, neigen Viruspartikel dazu, eine Weile zu verbleiben. Diese Partikel können keine Infektion auslösen, aber sie können zu einem positiven Testergebnis führen. [aus STAT News von Andrew Joseph](https://www.statnews.com/2020/04/20/everything-we-know-about-coronavirus-immunity-and-antibodies-and-plenty-we-still-dont/)
```

2020-05-08 09:05 UTC, merged